### ISSUE TITLE
typo in Detection > cascade

### ISSUE THREAD

**Issue by LauLauThom** [a-anjos/python-opencv#2]
Hi @a-anjos, very cool idea,
I think I spotted a tiny typo, in Detection > Cascade
Instead of `f.load` and `f.detectMultiScale`, it should be `c.load` and `c.detectMultiScale` since the variable `c` holds the cascade object

**Comment by a-anjos** [comment]
Hi @LauLauThom,
You are correct. Thanks for your observation. I've addressed it with this [commit](https://github.com/a-anjos/python-opencv/commit/9ab29c76388daf7bfe530a67e1b46dc141804b9e).
Cheers.
